config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('opac.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

# for django-debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

admin.site.site_header = "Django-OPAC 管理サイト"
admin.site.site_title = "Django-OPAC 管理サイト"
admin.site.index_title = "管理ホーム"

opac/urls.py
from django.urls import path

from . import views


app_name = 'opac'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('book/<int:pk>/',
         views.BookDetailView.as_view(), name='book_detail'),
]

opac/models/abstracts.py
from django.db import models


class TimeStampedModel(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateTimeField(
        '作成日時',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        '更新日時',
        auto_now=True
    )

opac/views/book_detail.py
from django.views.generic import DetailView

from opac.queries import BookDetailQuery, BookStocksQuery


class BookDetailView(DetailView):
    def get_queryset(self):
        return BookDetailQuery(self.kwargs['pk']).exec()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.kwargs['pk']
        context['stocks'] = BookStocksQuery(book_id).exec()
        return context

opac/views/index.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'opac/index.html'

opac/views/search.py
from django.contrib import messages
from django.shortcuts import render
from django.views.generic import ListView

from opac.queries import BookSearchQuery


class SearchView(ListView):
    template_name = 'opac/book_list.html'
    context_object_name = 'books'
    paginate_by = 20

    def render_index(self, request):
        return render(request, 'opac/index.html')

    def render_no_search_words(self, request):
        messsage = '検索語を入力してください。'
        messages.error(request, messsage, extra_tags='danger')
        return self.render_index(request)

    def render_no_books(self, request):
        messsage = '該当する書籍が見つかりませんでした。'
        messages.warning(request, messsage)
        return self.render_index(request)

    def dispatch(self, request, *args, **kwargs):
        if 'words' not in request.GET:
            return self.render_no_search_words(request)
        if request.GET['words'].split() == []:
            return self.render_no_search_words(request)
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        words = self.request.GET['words'].split()
        return BookSearchQuery(words).exec()

    def render_to_response(self, context, **response_kwargs):
        if not self.object_list:
            return self.render_no_books(self.request)
        return super().render_to_response(context, **response_kwargs)

opac/templates/opac/base.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
  <title>{% block meta_title %}{% endblock %} | Django-OPAC</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="icon" href="{% static 'opac/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'opac/css/bootstrap.min.css' %}">
  {% block extra_css %}{% endblock %}
</head>
<body style="overflow-y: scroll;">
  <header>
    <div class="container">
      <nav class="navbar navbar-expand navbar-light px-0 py-2">
        <a class="navbar-brand font-weight-light" style="font-size: 2.6rem;" href="{% url 'opac:index' %}">
          Django-OPAC
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" href="#" id="userMenu"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="#">マイページ</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">ログイン</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <main class="py-5 bg-light">
    <div class="container">
      {% if messages %}
      <div class="container">
        <div class="row">
          <div class="col-12 px-0">
            <div class="messages">
              {% for message in messages %}
              <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}

      {% block content %}{% endblock %}
    </div>
  </main>

  <footer class="py-5 text-center text-muted">
    <div class="container">
      <p class="mb-0">&copy; 2018 Ryuichi Sasaki</p>
    </div>
  </footer>

  <script src="{% static 'opac/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'opac/js/bootstrap.bundle.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</body>
</html>

opac/templates/opac/book_detail.html
{% extends 'opac/base.html' %}
{% load filters %}

{% block meta_title %}蔵書情報{% endblock %}

{% block content %}
      <h2 class="text-center font-weight-light pt-4 pb-5">{{ book.name }}</h2>

      <table class="table table-sm table-bordered table-hover mb-5">
        <caption class="text-center" style="caption-side: top; font-size: 1.2rem;">
          所蔵情報
        </caption>
        <thead class="thead-light">
          <tr>
            <th>所蔵場所</th>
            <th>蔵書番号</th>
            <th>状態</th>
          </tr>
        </thead>
        <tbody>
          {% for stock in stocks %}
          <tr>
            <td>{{ stock.library }}</td>
            <td>{{ stock.id }}</td>
            <td>
              {% if stock.is_lendable %}
              貸出可能
              {% elif stock.is_lent %}
              貸出中 [{{ stock.lending.actual_due_date }}返却期限]
              {% else %}
              取置中 [{{ stock.holding.expiration_date }}取置期限]
              {% endif %}
              {% if stock.is_reserved %}
              予約{{ stock.reservations.count }}人
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <table class="table table-sm mb-5">
        <caption class="text-center" style="caption-side: top; font-size: 1.2rem;">
          書籍詳細
        </caption>
        <tbody>
          <tr><th>書名</th><td>{{ book.name }}</td></tr>
          <tr><th>著者</th><td>{{ book.authors.all|names:', ' }}</td></tr>
          <tr><th>訳者</th><td>{{ book.translators.all|names:', ' }}</td></tr>
          <tr><th>出版者</th><td>{{ book.publisher.name }}</td></tr>
          <tr><th>発行日</th><td>{{ book.issue_date|default_if_none:'' }}</td></tr>
          <tr><th>大きさ</th><td>{{ book.size|default_if_none:'' }}</td></tr>
          <tr><th>ページ</th><td>{{ book.page|default_if_none:'' }}</td></tr>
          <tr><th>ISBN</th><td>{{ book.isbn|default_if_none:'' }}</td></tr>
        </tbody>
      </table>

      <a href="javascript:void(0);" onclick="window.history.back();">検索結果へ戻る</a>
{% endblock %}

opac/templates/opac/book_list.html
{% extends 'opac/base.html' %}
{% load filters %}

{% block meta_title %}検索結果{% endblock %}

{% block content %}
      <p class="mb-0">該当件数：{{ paginator.count }}件</p>
      <p style="font-size: 0.8rem;">({{ request.GET.words }})</p>

      {% if is_paginated %}
      {% include 'opac/paginations/pagination.html' %}
      {% endif %}

      <table class="table table-hover table-bordered">
        <thead class="thead-light">
          <tr>
            <th style="width: 30%">書名</th>
            <th style="width: 20%">著者</th>
            <th style="width: 20%">訳者</th>
            <th style="width: 15%">出版者</th>
            <th style="width: 15%">発行日</th>
          </tr>
        </thead>
        <tbody>
          {% for book in books %}
          <tr>
            <td><a href="{% url 'opac:book_detail' book.id %}">{{ book.name }}</a></td>
            <td>{{ book.authors.all|names:', ' }}</td>
            <td>{{ book.translators.all|names:', ' }}</td>
            <td>{{ book.publisher.name }}</td>
            <td>{{ book.issue_date|default_if_none:'' }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if is_paginated %}
      {% include 'opac/paginations/pagination.html' %}
      {% endif %}

      <div class="mt-5">
        <a href="{% url 'opac:index' %}">検索へ戻る</a>
      </div>
{% endblock %}

opac/templates/opac/index.html
{% extends 'opac/base.html' %}

{% block meta_title %}蔵書検索{% endblock %}

{% block content %}
      <form method="GET" action="{% url 'opac:search' %}" class="my-5">
        <div class="form-group my-4">
          <input type="text" name="words" class="form-control" autofocus required>
        </div>
        <div class="text-center">
          <button type="submit"
                  class="btn btn-primary"
                  style="display: inline-block; width: 140px">
            検索
          </button>
        </div>
      </form>
{% endblock %}

opac/templates/opac/paginations/pagination.html
{% load tags %}

<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link"
           href="?{% url_replace request 'page' page_obj.previous_page_number %}"
           aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% endif %}
    {% for linkpage in page_obj.paginator.page_range %}
      {% ifequal linkpage page_obj.number %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ linkpage }}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace request 'page' linkpage %}">{{ linkpage }}</a>
        </li>
    {% endifequal %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

opac/templates/opac/search.html
{% extends 'opac/base.html' %}

{% block meta_title %}蔵書検索{% endblock %}

{% block content %}
      <form method="GET" action="{% url 'opac:search' %}" class="my-5">
        <div class="form-group my-4">
          <input type="text" name="words" class="form-control" autofocus required>
        </div>
        <div class="text-center">
          <button type="submit"
                  class="btn btn-primary"
                  style="display: inline-block; width: 140px">
            検索
          </button>
        </div>
      </form>
{% endblock %}

opac/templates/opac/stock_list.html
{% extends 'opac/base.html' %}
{% load filters %}

{% block meta_title %}蔵書情報{% endblock %}

{% block content %}
      <h2 class="text-center font-weight-light pt-4 pb-5">{{ book.name }}</h2>

      <table class="table table-sm table-bordered table-hover mb-5">
        <caption class="text-center" style="caption-side: top; font-size: 1.2rem;">
          所蔵情報
        </caption>
        <thead class="thead-light">
          <tr>
            <th>所蔵場所</th>
            <th>蔵書番号</th>
            <th>状態</th>
          </tr>
        </thead>
        <tbody>
          {% for stock in stocks %}
          <tr>
            <td>{{ stock.library }}</td>
            <td>{{ stock.id }}</td>
            <td>
              {% if stock.is_lendable %}
              貸出可能
              {% elif stock.is_lent %}
              貸出中 [{{ stock.lending.actual_due_date }}返却期限]
              {% else %}
              取置中 [{{ stock.holding.expiration_date }}取置期限]
              {% endif %}
              {% if stock.is_reserved %}
              予約{{ stock.reservations.count }}人
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      <table class="table table-sm mb-5">
        <caption class="text-center" style="caption-side: top; font-size: 1.2rem;">
          書籍詳細
        </caption>
        <tbody>
          <tr><th>書名</th><td>{{ book.name }}</td></tr>
          <tr><th>著者</th><td>{{ book.authors.all|names:', ' }}</td></tr>
          <tr><th>訳者</th><td>{{ book.translators.all|names:', ' }}</td></tr>
          <tr><th>出版者</th><td>{{ book.publisher.name }}</td></tr>
          <tr><th>発行日</th><td>{{ book.issue_date|default_if_none:'' }}</td></tr>
          <tr><th>大きさ</th><td>{{ book.size|default_if_none:'' }}</td></tr>
          <tr><th>ページ</th><td>{{ book.page|default_if_none:'' }}</td></tr>
          <tr><th>ISBN</th><td>{{ book.isbn|default_if_none:'' }}</td></tr>
        </tbody>
      </table>

      <a href="javascript:void(0);" onclick="window.history.back();">検索結果へ戻る</a>
{% endblock %}